### ISSUE TITLE
Hardening

### ISSUE THREAD

**Issue by JOduMonT** [SS88UK/VestaCP-Server-Installer#1]
When I run your [hardening config](https://vestacp.ss88.uk/VestaCP_Installer/CentOS7/sysctl.conf-eth0) on FreshInstall CentOS 7

I receive message Invalid argument about net.ipv4.ip_local_port_range

I look [online](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Tuning_and_Optimizing_Red_Hat_Enterprise_Linux_for_Oracle_9i_and_10g_Databases/sect-Oracle_9i_and_10g_Tuning_Guide-Adjusting_Network_Settings-Changing_Network_Kernel_Settings.html) and it seams fine but my CentOS don't digest it. ;(

it is working for you ?

**Comment by Neoboffin** [comment]
@jodumont Yes, it works for me. I have dedicates and VPS. I know that argument does not work on Digital Ocean (I think it was DO). Some providers change their config to only allow certain arguments to be modified.
